//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Clients.FCB.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Clients.FCB.Shared.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string _false {
            get {
                return ResourceManager.GetString("false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string _true {
            get {
                return ResourceManager.GetString("true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string add_family_member {
            get {
                return ResourceManager.GetString("add_family_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        public static string add_income {
            get {
                return ResourceManager.GetString("add_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        public static string adult {
            get {
                return ResourceManager.GetString("adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount adults.
        /// </summary>
        public static string adult_amount {
            get {
                return ResourceManager.GetString("adult_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string adults {
            get {
                return ResourceManager.GetString("adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string applicant {
            get {
                return ResourceManager.GetString("applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants.
        /// </summary>
        public static string applicants {
            get {
                return ResourceManager.GetString("applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking rent.
        /// </summary>
        public static string asking_rent {
            get {
                return ResourceManager.GetString("asking_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign employee.
        /// </summary>
        public static string assigned_employee {
            get {
                return ResourceManager.GetString("assigned_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom.
        /// </summary>
        public static string bedroom {
            get {
                return ResourceManager.GetString("bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrooms.
        /// </summary>
        public static string bedrooms {
            get {
                return ResourceManager.GetString("bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string child {
            get {
                return ResourceManager.GetString("child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child discount.
        /// </summary>
        public static string child_discount {
            get {
                return ResourceManager.GetString("child_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string children {
            get {
                return ResourceManager.GetString("children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount children.
        /// </summary>
        public static string children_amount {
            get {
                return ResourceManager.GetString("children_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        public static string complex {
            get {
                return ResourceManager.GetString("complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date construction.
        /// </summary>
        public static string construction_date {
            get {
                return ResourceManager.GetString("construction_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction costs.
        /// </summary>
        public static string construction_price {
            get {
                return ResourceManager.GetString("construction_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        public static string contact_information {
            get {
                return ResourceManager.GetString("contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract amount.
        /// </summary>
        public static string contract_amount {
            get {
                return ResourceManager.GetString("contract_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of birth.
        /// </summary>
        public static string country_of_birth {
            get {
                return ResourceManager.GetString("country_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current lease agreement.
        /// </summary>
        public static string current_lease_agreement {
            get {
                return ResourceManager.GetString("current_lease_agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rent.
        /// </summary>
        public static string current_rent {
            get {
                return ResourceManager.GetString("current_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current tenant.
        /// </summary>
        public static string current_tenant {
            get {
                return ResourceManager.GetString("current_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor code.
        /// </summary>
        public static string debtor_code {
            get {
                return ResourceManager.GetString("debtor_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a description....
        /// </summary>
        public static string description_placeholder {
            get {
                return ResourceManager.GetString("description_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string employer {
            get {
                return ResourceManager.GetString("employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string family {
            get {
                return ResourceManager.GetString("family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string family_number_of_adults {
            get {
                return ResourceManager.GetString("family_number_of_adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string family_number_of_children {
            get {
                return ResourceManager.GetString("family_number_of_children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School going.
        /// </summary>
        public static string family_number_of_school_going {
            get {
                return ResourceManager.GetString("family_number_of_school_going", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family situation.
        /// </summary>
        public static string family_situation {
            get {
                return ResourceManager.GetString("family_situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string gender_female {
            get {
                return ResourceManager.GetString("gender.female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string gender_male {
            get {
                return ResourceManager.GetString("gender.male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string gender_other {
            get {
                return ResourceManager.GetString("gender.other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground lease.
        /// </summary>
        public static string ground_lease {
            get {
                return ResourceManager.GetString("ground_lease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested in buying.
        /// </summary>
        public static string home_seeker_interested_in_buying {
            get {
                return ResourceManager.GetString("home_seeker_interested_in_buying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bedrooms.
        /// </summary>
        public static string home_seeker_number_of_bedrooms {
            get {
                return ResourceManager.GetString("home_seeker_number_of_bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred neighborhood.
        /// </summary>
        public static string home_seeker_preferred_neighborhood {
            get {
                return ResourceManager.GetString("home_seeker_preferred_neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred neighborhood 1.
        /// </summary>
        public static string home_seeker_preferred_neighborhood_1 {
            get {
                return ResourceManager.GetString("home_seeker_preferred_neighborhood_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred neighborhood 2.
        /// </summary>
        public static string home_seeker_preferred_neighborhood_2 {
            get {
                return ResourceManager.GetString("home_seeker_preferred_neighborhood_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred neighborhood 3.
        /// </summary>
        public static string home_seeker_preferred_neighborhood_3 {
            get {
                return ResourceManager.GetString("home_seeker_preferred_neighborhood_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string home_seeker_since {
            get {
                return ResourceManager.GetString("home_seeker_since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgency.
        /// </summary>
        public static string home_seeker_urgency {
            get {
                return ResourceManager.GetString("home_seeker_urgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House code.
        /// </summary>
        public static string house_code {
            get {
                return ResourceManager.GetString("house_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House information.
        /// </summary>
        public static string house_information {
            get {
                return ResourceManager.GetString("house_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House rent.
        /// </summary>
        public static string house_rent {
            get {
                return ResourceManager.GetString("house_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        public static string houses {
            get {
                return ResourceManager.GetString("houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string income {
            get {
                return ResourceManager.GetString("income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Type.
        /// </summary>
        public static string income_type {
            get {
                return ResourceManager.GetString("income_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code.
        /// </summary>
        public static string itemCode {
            get {
                return ResourceManager.GetString("itemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land registry number.
        /// </summary>
        public static string land_registry_number {
            get {
                return ResourceManager.GetString("land_registry_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease agreements.
        /// </summary>
        public static string lease_agreements {
            get {
                return ResourceManager.GetString("lease_agreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left home.
        /// </summary>
        public static string left_home {
            get {
                return ResourceManager.GetString("left_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main contact.
        /// </summary>
        public static string main_contact {
            get {
                return ResourceManager.GetString("main_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market value.
        /// </summary>
        public static string market_value {
            get {
                return ResourceManager.GetString("market_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum rent.
        /// </summary>
        public static string max_rent {
            get {
                return ResourceManager.GetString("max_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount minor.
        /// </summary>
        public static string minor_amount {
            get {
                return ResourceManager.GetString("minor_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly income.
        /// </summary>
        public static string monthly_income {
            get {
                return ResourceManager.GetString("monthly_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string neighborhood {
            get {
                return ResourceManager.GetString("neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client.
        /// </summary>
        public static string new_client {
            get {
                return ResourceManager.GetString("new_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New income.
        /// </summary>
        public static string new_income {
            get {
                return ResourceManager.GetString("new_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new person.
        /// </summary>
        public static string new_person {
            get {
                return ResourceManager.GetString("new_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of bedrooms.
        /// </summary>
        public static string number_of_bedrooms {
            get {
                return ResourceManager.GetString("number_of_bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family count.
        /// </summary>
        public static string number_of_residents {
            get {
                return ResourceManager.GetString("number_of_residents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string prefix {
            get {
                return ResourceManager.GetString("prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous lease agreements.
        /// </summary>
        public static string previous_lease_agreement {
            get {
                return ResourceManager.GetString("previous_lease_agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string relation {
            get {
                return ResourceManager.GetString("relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        public static string relations {
            get {
                return ResourceManager.GetString("relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation costs.
        /// </summary>
        public static string renovation_costs {
            get {
                return ResourceManager.GetString("renovation_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date renovation.
        /// </summary>
        public static string renovation_date {
            get {
                return ResourceManager.GetString("renovation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent amount.
        /// </summary>
        public static string rent_amount {
            get {
                return ResourceManager.GetString("rent_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent base points.
        /// </summary>
        public static string rent_base_points {
            get {
                return ResourceManager.GetString("rent_base_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent base price.
        /// </summary>
        public static string rent_base_price {
            get {
                return ResourceManager.GetString("rent_base_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status house.
        /// </summary>
        public static string rent_status {
            get {
                return ResourceManager.GetString("rent_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string rented {
            get {
                return ResourceManager.GetString("rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School going.
        /// </summary>
        public static string schoolgoing {
            get {
                return ResourceManager.GetString("schoolgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select employee.
        /// </summary>
        public static string select_employee {
            get {
                return ResourceManager.GetString("select_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set price.
        /// </summary>
        public static string set_price {
            get {
                return ResourceManager.GetString("set_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meters (BVO).
        /// </summary>
        public static string square_meters_bvo {
            get {
                return ResourceManager.GetString("square_meters_bvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meters (FCB).
        /// </summary>
        public static string square_meters_fcb {
            get {
                return ResourceManager.GetString("square_meters_fcb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meters (GO).
        /// </summary>
        public static string square_meters_go {
            get {
                return ResourceManager.GetString("square_meters_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tenant selection.
        /// </summary>
        public static string start_house_selection {
            get {
                return ResourceManager.GetString("start_house_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        public static string surface {
            get {
                return ResourceManager.GetString("surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date taxation.
        /// </summary>
        public static string taxation_date {
            get {
                return ResourceManager.GetString("taxation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary discount.
        /// </summary>
        public static string temporary_discount {
            get {
                return ResourceManager.GetString("temporary_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string tenant {
            get {
                return ResourceManager.GetString("tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants.
        /// </summary>
        public static string tenants {
            get {
                return ResourceManager.GetString("tenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unil.
        /// </summary>
        public static string until {
            get {
                return ResourceManager.GetString("until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update client.
        /// </summary>
        public static string update_client {
            get {
                return ResourceManager.GetString("update_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly amount.
        /// </summary>
        public static string yearly_amount {
            get {
                return ResourceManager.GetString("yearly_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly income.
        /// </summary>
        public static string yearly_income {
            get {
                return ResourceManager.GetString("yearly_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly income class.
        /// </summary>
        public static string yearly_income_class {
            get {
                return ResourceManager.GetString("yearly_income_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly total income.
        /// </summary>
        public static string yearly_total_income {
            get {
                return ResourceManager.GetString("yearly_total_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        public static string years_old {
            get {
                return ResourceManager.GetString("years_old", resourceCulture);
            }
        }
    }
}
