//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebula.Shared.Clients.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebula.Shared.Clients.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string administration {
            get {
                return ResourceManager.GetString("administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to application.
        /// </summary>
        public static string back_to_application {
            get {
                return ResourceManager.GetString("back_to_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string back_to_home {
            get {
                return ResourceManager.GetString("back_to_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your language.
        /// </summary>
        public static string change_language_description {
            get {
                return ResourceManager.GetString("change_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing password....
        /// </summary>
        public static string changing_password {
            get {
                return ResourceManager.GetString("changing_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cache.
        /// </summary>
        public static string clear_cache {
            get {
                return ResourceManager.GetString("clear_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the cache?.
        /// </summary>
        public static string clear_cache_confirmation {
            get {
                return ResourceManager.GetString("clear_cache_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string clear_filters {
            get {
                return ResourceManager.GetString("clear_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing cache....
        /// </summary>
        public static string clearing_cache {
            get {
                return ResourceManager.GetString("clearing_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string columns {
            get {
                return ResourceManager.GetString("columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password.
        /// </summary>
        public static string confirmation_password {
            get {
                return ResourceManager.GetString("confirmation_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string dark_mode {
            get {
                return ResourceManager.GetString("dark_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string exporting {
            get {
                return ResourceManager.GetString("exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string language_en {
            get {
                return ResourceManager.GetString("language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string language_nl {
            get {
                return ResourceManager.GetString("language_nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string my_account {
            get {
                return ResourceManager.GetString("my_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string my_profile {
            get {
                return ResourceManager.GetString("my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data added yet.
        /// </summary>
        public static string no_data_description {
            get {
                return ResourceManager.GetString("no_data_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string no_results {
            get {
                return ResourceManager.GetString("no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results available based on your filter criteria.
        /// </summary>
        public static string no_results_description {
            get {
                return ResourceManager.GetString("no_results_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string redirecting {
            get {
                return ResourceManager.GetString("redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a {0}....
        /// </summary>
        public static string select_a {
            get {
                return ResourceManager.GetString("select_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an {0}....
        /// </summary>
        public static string select_an {
            get {
                return ResourceManager.GetString("select_an", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in attempt failed.
        /// </summary>
        public static string sign_in_attempt_failed {
            get {
                return ResourceManager.GetString("sign_in_attempt_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string signing_in {
            get {
                return ResourceManager.GetString("signing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string sites {
            get {
                return ResourceManager.GetString("sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
